### ISSUE TITLE
list 페이지 search시

### ISSUE THREAD

**Issue by 100space** [100space/project2#103]
list page에서 search기능 사용시 
데이터의 종류가 많으면 리스트 전체를 불러오기 때문에 기존 ui랑 맞지 않아서 body부분이 길어져 ui가 깨짐..

1. 라우터를 변경해서 새로운 로직으로 데이터를 반환하는 방법
2. ui를 변경하는 방법

**Comment by Hynn-Hyunwoong** [comment]
UI 수정으로 해결
